export const GET_RESUME_DATA_REQUEST = 'GET_RESUME_DATA_REQUEST';
export const GET_RESUME_DATA_SUCCESS = 'GET_RESUME_DATA_SUCCESS';
export const GET_RESUME_DATA_FAILED = 'GET_RESUME_DATA_FAILED';

export const SAVE_RESUME_DATA_REQUEST = 'SAVE_RESUME_DATA_REQUEST';
export const SAVE_RESUME_DATA_SUCCESS = 'SAVE_RESUME_DATA_SUCCESS';
export const SAVE_RESUME_DATA_FAILED = 'SAVE_RESUME_DATA_FAILED';

export const UPDATE_RESUME_DATA_REQUEST = 'UPDATE_RESUME_DATA_REQUEST';
export const UPDATE_RESUME_DATA_SUCCESS = 'UPDATE_RESUME_DATA_SUCCESS';
export const UPDATE_RESUME_DATA_FAILED = 'UPDATE_RESUME_DATA_FAILED';
